import './start';
import './reset-menu';
import './weekday-schedule';
import './now';
import './set-follow-teacher';
import './call-schedule';
import './more';
import './contacts';
import './admin-schedule';
